apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-threedee
  labels:
    sensors.argoproj.io/controller-instanceid: axis
spec:
  signals:
    - name: webhook
      webhook:
        endpoint: /3D
        method: POST
  triggers:
    - name: argo-workflow
      resource:
        namespace: default
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        # The parameters from the workflow are overridden by the webhook's message
        parameters:
          - src:
              signal: webhook
              path: Records.0.s3.object.key
            dest: spec.arguments.parameters.0.value
        source:
          inline: |
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: log-analyzer-workflow-
              spec:
                entrypoint: log-analyzer
                arguments:
                  parameters:
                  - name: webhook
                    value: overriddenvalue
                volumes:
                - name: workdir
                  persistentVolumeClaim:
                    claimName: log-analyzer-pvc
                templates:
                - name: log-analyzer
                  inputs:
                    parameters:
                    - name: webhook
                      value: "{{arguments.parameters.webhook}}"
                    artifacts:
                    - name: CODE
                      git: 
                        repo: https://github.com/EliZucker/Argo-Workflow-Test.git
                  dag:
                    tasks:
                    - name: APPLY-PVC
                      template: apply-pvc
                    - name: WEBHOOK
                      template: redeploy-webhook
                      arguments:
                        artifacts:
                        - name: CODE
                          from: "{{inputs.artifacts.CODE}}"
                    - name: TFJOB
                      template: tfjob
                      dependencies: [APPLY-PVC, WEBHOOK]
                    - name: OutputTFJOB
                      template: output
                      dependencies: [TFJOB]

                - name: apply-pvc
                  resource:
                    action: apply
                    manifest: |
                      kind: PersistentVolumeClaim
                      apiVersion: v1
                      metadata:
                        name: log-analyzer-pvc
                      spec:
                        accessModes: [ "ReadWriteOnce" ]
                        resources:
                          requests:
                            storage: 1Gi

                - name: redeploy-webhook
                  inputs:
                    artifacts:
                    - name: CODE
                      path: /root/
                  container:
                    image: lachlanevenson/k8s-kubectl
                    command: [sh, -c]
                    args: ["
                      POD=$(kubectl get pod -l app=webhook -o jsonpath='{.items[0].metadata.name}') &&
                      kubectl delete sensor webhook-threedee &&
                      kubectl delete pod $POD &&
                      kubectl create -f /root/model/webhook_logs.yaml
                    
                    "]

                - name: output
                  container:
                    volumeMounts: 
                    - name: workdir
                      mountPath: /mnt/vol
                    image: alpine:latest
                  outputs:
                    artifacts:
                    - name: training-logs
                      path: /mnt/vol/model

                
                - name: tfjob
                  resource:
                    action: create
                    successCondition: status.tfReplicaStatuses.Worker.succeeded > 0
                    failureCondition: status.tfReplicaStatuses.Worker.failed > 0
                    manifest: |
                      apiVersion: kubeflow.org/v1alpha2
                      kind: TFJob
                      metadata:
                        ownerReferences:
                        - apiVersion: argoproj.io/v1alpha1
                          blockOwnerDeletion: true
                          kind: Workflow
                          name: "{{workflow.name}}"
                          uid: "{{workflow.uid}}"
                        labels:
                          ksonnet.io/component: log-analyzer
                        generateName: log-analyzer-
                        namespace: default
                      spec:
                        tfReplicaSpecs:
                          Worker:
                            replicas: 1
                            template:
                              spec:
                                volumes:
                                - name: workdir
                                  persistentVolumeClaim:
                                    claimName: log-analyzer-pvc
                                containers:
                                - args: ["
                                  apt-get update &&
                                  apt-get install git -y &&
                                  wget https://dl.minio.io/server/minio/release/linux-amd64/minio &&
                                  chmod +x minio &&
                                  ./minio server /data &&
                                  mcc
                                  git clone https://github.com/alexmt/log-analyzer.git &&
                                  cd log-analyzer/model &&
                                  python3 ./train.py --input-path sample-data/logs.txt --model-dir-path /mnt/vol/model
                                  "]
                                  command:
                                  - /bin/sh
                                  - -c
                                  image: tensorflow/tensorflow:latest-gpu-py3
                                  name: tensorflow
                                  volumeMounts: 
                                  - name: workdir
                                    mountPath: /mnt/vol
                                  resources:
                                    limits:
                                      nvidia.com/gpu: "1"
                                restartPolicy: OnFailure
                                

                                  
                                              